### ISSUE TITLE
为什么总是跳转浏览器，而不是在app 里面？

### ISSUE THREAD

**Issue by jb77799** [zzzDaEMoNzzz/cordova-cra-live-reload#1]
你好：
    cordova-cra-live-reload run ios 我执行这个，成功启动模拟器，但是打开了模拟器的浏览器，app 一直自动跳转到模拟器。 最简易的脚手架构建的～

**Comment by jb77799** [comment]
有什么联系方式可以联系你吗？

**Comment by vladimir-kurlov** [comment]
你好。 启动时禁用浏览器打开。

我不确定我是否正确理解你。 你能用英文写吗？
